apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      version: blue
  template:
    metadata:
      labels:
        app: auth-service
        version: blue
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
