apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
      version: blue
  template:
    metadata:
      labels:
        app: transaction-service
        version: blue
    spec:
      containers:
        - name: transaction-service
          image: transaction-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
