apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-coinbase-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimer: Delete
  volumeMode: Filesystem
  dataSource:
    persistentVolumeClaim:
      claimName: coinbase-data
