apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    version: blue
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-green
spec:
  selector:
    version: green
