name: CI/CD Pipeline for Coinbase Monitoring

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images for Services
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/services/auth-service ./services/auth-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/services/transaction-service ./services/transaction-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/services/monitoring-service ./services/monitoring-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/services/notification-service ./services/notification-service

      - name: List Docker Images
        run: docker images

      - name: Push Docker Images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/coinbase/services/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/coinbase/services/transaction-service
          docker push ${{ secrets.DOCKER_USERNAME }}/coinbase/services/monitoring-service
          docker push ${{ secrets.DOCKER_USERNAME }}/coinbase/services/notification-service
