name: CI/CD Pipeline for Coinbase Monitoring

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images for Services
        run: |
          docker build -t your-dockerhub-repo/auth-service ./auth-service
          docker build -t your-dockerhub-repo/transaction-service ./transaction-service
          docker build -t your-dockerhub-repo/monitoring-service ./monitoring-service
          docker build -t your-dockerhub-repo/notification-service ./notification-service

      - name: Push Docker Images to Docker Hub
        run: |
          docker push your-dockerhub-repo/auth-service
          docker push your-dockerhub-repo/transaction-service
          docker push your-dockerhub-repo/monitoring-service
          docker push your-dockerhub-repo/notification-service
